### ISSUE TITLE
he DSC Extension received an incorrect input: An error occurred while executing script or module 'aks_setup.ps1'

### ISSUE THREAD

**Issue by danfinn** [aidapsibr/aks-prometheus-windows-exporter#1]
We ran into the following error when running the Deploy-PrometheusWindowsExporter function:

```
PS C:\Users\pwadmin> Deploy-PrometheusWindowsExporter -subscription "$subscription" -resourceGroup "$resource_group_name"Checking $subscription/$resource_group_name for windows vmss that need powershell dsc installedInstalling DSC on the following VMSS:
akswinInstalling DSC on vmss akswin...
Updating instances on vmss akswin...
ERROR: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: "The DSC Extension received an incorrect input: An error occurred while executing script or module 'aks_setup.ps1': The term 'C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\bin\..\DSCWork\aks_setup.1\aks_setup.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..

Please correct the input and retry executing the extension."More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot
Code: VMExtensionProvisioningError

Message: VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: "The DSC Extension received an incorrect input: An error occurred while executing script or module 'aks_setup.ps1': The term 'C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\bin\..\DSCWork\aks_setup.1\aks_setup.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..

Please correct the input and retry executing the extension."More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot
DSC installation complete on vmss akswinAll windows vmss have powershell dsc extension installed in $subscription/$resource_group_name
Azure Desired State Configuration Extension Handler - Azure Virtual Machines
Upload and apply a PowerShell DSC configuration on an Azure VM using DSC Extension
```

It looks like it's failing to run because of an issue with the powershell script.  Subsequent runs result in nothing happening because it thinks the powershell dsc is already installed.

**Comment by aidapsibr** [comment]
It looks like your path may be wrong to the script. `DSCWork\aks_setup.1\aks_setup.ps1` did you create your own zip file named DSCWork? You may have nested the script more than intended in the zip or in the install.ps1

I also fixed what I think is a bug in my paths.
https://github.com/aidapsibr/aks-prometheus-windows-exporter/commit/28bd6456dc0566cbf84ae667d2e7e9a63bef8742

**Comment by danfinn** [comment]
I did not create my own zip, there was no mention of that in the README.

Following the instructions, all that was done was clone the repo, get the Deploy-PrometheusWindowsExporter setup locally and then run it as shown above providing the subscription ID and the resource group for the node pool.

**Comment by danfinn** [comment]
One other thing I should mention.  We got that error after the function had been running for about 15 minutes, then hitting control-c gave us that error output.  This seems like it should be plenty of time for this finish but is there any chance it takes longer than that?

**Comment by aidapsibr** [comment]
I think I found the other path issue, you can try running this to remove the extension and try again with my changes.

```az vmss extension delete `
            --name "Microsoft.Powershell.DSC" `
            --subscription $subscription `
            --resource-group $resourceGroup `
            --vmss-name $vmssName;    ```

**Comment by aidapsibr** [comment]
> One other thing I should mention. We got that error after the function had been running for about 15 minutes, then hitting control-c gave us that error output. This seems like it should be plenty of time for this finish but is there any chance it takes longer than that?

It should fail quickly, but the script is just calling Azure CLI there, so they may have poor behavior on error unfortunately.

**Comment by danfinn** [comment]
I just let it run again until failure on a new node pool.  Same error, after around 15 minutes.  It seems to be quite slow to fail but our az commands are working and responding normally.

**Comment by danfinn** [comment]
I'm unable to delete the vmss extension.  When I try I get the same error as above, about it not able to find aks_setup.ps1.

```
(VMExtensionProvisioningError) VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: "The DSC Extension received an incorrect input: An error occurred while executing script or module 'aks_setup.ps1':  The term 'C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\bin\..\DSCWork\aks_setup.1\aks_setup.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..
Please correct the input and retry executing the extension."

More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: "The DSC Extension received an incorrect input: An error occurred while executing script or module 'aks_setup.ps1':  The term 'C:\Packages\Plugins\Microsoft.Powershell.DSC\2.83.2.0\bin\..\DSCWork\aks_setup.1\aks_setup.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..
Please correct the input and retry executing the extension."

More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot
```

**Comment by aidapsibr** [comment]
For the delay, you can try adding --no-wait and checking status with CLI commands or in portal instead,

https://medium.com/@azjacks0n/how-to-fix-broken-extensions-on-an-azure-virtual-machine-scaleset-96498b74cc79
Here is another doc on removing the extension using powershell, or I'd recommend to just remove them in the portal if thats an option. Installing wont work until then unfortunately even with the --force-update flag we found.

**Comment by danfinn** [comment]
I'm brute forcing it.  I deleted the node pool and am in the process of creating a new one now to re-run on.

**Comment by danfinn** [comment]
It looks like that might have fixed it.  It still took about 10 minutes but it applied it this time around, no errors.  Now to verify that it's actually running...

**Comment by danfinn** [comment]
Confirmed that windows exporter is installed and running.  Thanks!
